server:
  port: 9011

spring:
  application:
    name: alibaba-seata-order-service
  cloud:
    nacos:
      discovery:
        server-addr: 112.126.59.115:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
    alibaba:
      seata:
        tx-service-group: seata_tx_group
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order?serverTimezone=UTC
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cloud.domain
  configuration:
    map-underscore-to-camel-case: true
